TRANSLATIONS = {

    "English": {
        "Dashboard": "Dashboard",
        "Products": "Products",
        "Add Product": "Add Product",
        "Inventory": "Inventory",
        "AI Tools": "AI Tools",
        "Image Enhancer": "Image Enhancer",
        "Voice Input": "Voice Input",
        "Smart Catalog": "Smart Catalog",
        "AI Pricing": "AI Pricing",
        "Business": "Business",
        "Market": "Market",
        "Account": "Account",
        "Settings": "Settings",
        "Logout": "Logout",

        "Welcome": "Welcome",
        "Welcome to CRAFTNOVA AI": "Welcome to CRAFTNOVA AI",
        "Your AI-powered craft business assistant": "Your AI-powered craft business assistant",

        "Name": "Name",
        "Email": "Email",
        "Language": "Language",
        "Craft Category": "Craft Category",
        "Business Name": "Business Name",

        "Recent Products": "Recent Products",
        "Product Name": "Product Name",
        "Category": "Category",
        "Material": "Material",
        "Color": "Color",
        "Size": "Size",
        "Description": "Description",
        "Price": "Price",
        "Actions": "Actions",

        "No products found": "No products found",
        "Add your first product": "Add your first product",

        "Save": "Save",
        "Save Changes": "Save Changes",
        "Cancel": "Cancel",
        "Delete": "Delete",
        "Edit": "Edit",
        "Search": "Search",
        "Submit": "Submit",
        "Back": "Back",
        "Generate": "Generate",
        "Upload": "Upload",
        "Download": "Download",
        "Process": "Process",
        "Start": "Start",
        "Stop": "Stop",

        "Add New Product": "Add New Product",
        "Product Details": "Product Details",
        "Enter product name": "Enter product name",
        "Enter category": "Enter category",
        "Enter material": "Enter material",
        "Enter color": "Enter color",
        "Enter size": "Enter size",
        "Enter description": "Enter description",
        "Enter price": "Enter price",
        "Product Image": "Product Image",

        "Inventory Management": "Inventory Management",
        "Search products": "Search products",
        "No products available": "No products available",

        "Enhance Product Image": "Enhance Product Image",
        "Upload an image and let AI improve it": "Upload an image and let AI improve it",
        "Original Image": "Original Image",
        "Enhanced Image": "Enhanced Image",
        "Enhance Image": "Enhance Image",

        "Voice Product Entry": "Voice Product Entry",
        "Speak your product details": "Speak your product details",
        "Start Voice Input": "Start Voice Input",
        "Stop Voice Input": "Stop Voice Input",
        "Product Type": "Product Type",
        "Transcript": "Transcript",
        "Use Voice Details": "Use Voice Details",

        "Smart Catalog": "Smart Catalog",
        "Generate a professional catalog using AI": "Generate a professional catalog using AI",
        "Generate Catalog": "Generate Catalog",
        "Catalog Result": "Catalog Result",

        "AI Pricing Assistant": "AI Pricing Assistant",
        "Get an AI-based price recommendation": "Get an AI-based price recommendation",
        "Material Cost": "Material Cost",
        "Labour Cost": "Labour Cost",
        "Production Cost": "Production Cost",
        "Market Information": "Market Information",
        "Get Price Recommendation": "Get Price Recommendation",
        "Recommended Price": "Recommended Price",
        "Price Range": "Price Range",
        "Reason": "Reason",
        "Market Consideration": "Market Consideration",

        "Market Linkage": "Market Linkage",
        "Connect your products with potential buyers": "Connect your products with potential buyers",
        "Product Showcase": "Product Showcase",
        "Buyer Visibility": "Buyer Visibility",
        "Market Visibility": "Market Visibility",

        "Account Settings": "Account Settings",
        "Select Language": "Select Language",
        "English": "English",
        "Tamil": "Tamil",
        "Kannada": "Kannada",
        "Telugu": "Telugu",
        "Hindi": "Hindi",
        "Malayalam": "Malayalam",
        "Language updated successfully": "Language updated successfully",

        "Login": "Login",
        "Register": "Register",
        "Password": "Password",
        "Confirm Password": "Confirm Password",
        "Create Account": "Create Account",
        "Already have an account?": "Already have an account?",
        "Don't have an account?": "Don't have an account?",
        "Login to CRAFTNOVA AI": "Login to CRAFTNOVA AI",
        "Create your CRAFTNOVA AI account": "Create your CRAFTNOVA AI account",

        "AI-powered marketplace assistant for artisans": "AI-powered marketplace assistant for artisans",
        "Craft Business": "Craft Business",
        "Handmade Products": "Handmade Products"
    },

    "Tamil": {
        "Dashboard": "முகப்பு",
        "Products": "தயாரிப்புகள்",
        "Add Product": "தயாரிப்பு சேர்க்க",
        "Inventory": "சரக்கு",
        "AI Tools": "AI கருவிகள்",
        "Image Enhancer": "பட மேம்படுத்தி",
        "Voice Input": "குரல் உள்ளீடு",
        "Smart Catalog": "ஸ்மார்ட் பட்டியல்",
        "AI Pricing": "AI விலை நிர்ணயம்",
        "Business": "வணிகம்",
        "Market": "சந்தை",
        "Account": "கணக்கு",
        "Settings": "அமைப்புகள்",
        "Logout": "வெளியேறு",

        "Welcome": "வரவேற்கிறோம்",
        "Welcome to CRAFTNOVA AI": "CRAFTNOVA AI-க்கு வரவேற்கிறோம்",
        "Your AI-powered craft business assistant": "உங்கள் AI அடிப்படையிலான கைவினை வணிக உதவியாளர்",

        "Name": "பெயர்",
        "Email": "மின்னஞ்சல்",
        "Language": "மொழி",
        "Craft Category": "கைவினை வகை",
        "Business Name": "வணிகப் பெயர்",

        "Recent Products": "சமீபத்திய தயாரிப்புகள்",
        "Product Name": "தயாரிப்பு பெயர்",
        "Category": "வகை",
        "Material": "பொருள்",
        "Color": "நிறம்",
        "Size": "அளவு",
        "Description": "விளக்கம்",
        "Price": "விலை",
        "Actions": "செயல்கள்",

        "No products found": "தயாரிப்புகள் எதுவும் இல்லை",
        "Add your first product": "உங்கள் முதல் தயாரிப்பைச் சேர்க்கவும்",

        "Save": "சேமி",
        "Save Changes": "மாற்றங்களைச் சேமி",
        "Cancel": "ரத்து செய்",
        "Delete": "நீக்கு",
        "Edit": "திருத்து",
        "Search": "தேடு",
        "Submit": "சமர்ப்பி",
        "Back": "பின் செல்ல",
        "Generate": "உருவாக்கு",
        "Upload": "பதிவேற்று",
        "Download": "பதிவிறக்கு",
        "Process": "செயலாக்கு",
        "Start": "தொடங்கு",
        "Stop": "நிறுத்து",

        "Add New Product": "புதிய தயாரிப்பைச் சேர்க்கவும்",
        "Product Details": "தயாரிப்பு விவரங்கள்",
        "Enter product name": "தயாரிப்பு பெயரை உள்ளிடவும்",
        "Enter category": "வகையை உள்ளிடவும்",
        "Enter material": "பொருளை உள்ளிடவும்",
        "Enter color": "நிறத்தை உள்ளிடவும்",
        "Enter size": "அளவை உள்ளிடவும்",
        "Enter description": "விளக்கத்தை உள்ளிடவும்",
        "Enter price": "விலையை உள்ளிடவும்",
        "Product Image": "தயாரிப்பு படம்",

        "Inventory Management": "சரக்கு மேலாண்மை",
        "Search products": "தயாரிப்புகளைத் தேடுங்கள்",
        "No products available": "தயாரிப்புகள் எதுவும் கிடைக்கவில்லை",

        "Enhance Product Image": "தயாரிப்பு படத்தை மேம்படுத்தவும்",
        "Upload an image and let AI improve it": "ஒரு படத்தைப் பதிவேற்றி AI மூலம் மேம்படுத்தவும்",
        "Original Image": "அசல் படம்",
        "Enhanced Image": "மேம்படுத்தப்பட்ட படம்",
        "Enhance Image": "படத்தை மேம்படுத்து",

        "Voice Product Entry": "குரல் மூலம் தயாரிப்பு பதிவு",
        "Speak your product details": "உங்கள் தயாரிப்பு விவரங்களைப் பேசுங்கள்",
        "Start Voice Input": "குரல் உள்ளீட்டைத் தொடங்கு",
        "Stop Voice Input": "குரல் உள்ளீட்டை நிறுத்து",
        "Product Type": "தயாரிப்பு வகை",
        "Transcript": "பதிவு செய்யப்பட்ட குரல்",
        "Use Voice Details": "குரல் விவரங்களைப் பயன்படுத்து",

        "Smart Catalog": "ஸ்மார்ட் பட்டியல்",
        "Generate a professional catalog using AI": "AI மூலம் தொழில்முறை பட்டியலை உருவாக்கவும்",
        "Generate Catalog": "பட்டியலை உருவாக்கு",
        "Catalog Result": "பட்டியல் முடிவு",

        "AI Pricing Assistant": "AI விலை நிர்ணய உதவியாளர்",
        "Get an AI-based price recommendation": "AI அடிப்படையிலான விலை பரிந்துரையைப் பெறுங்கள்",
        "Material Cost": "பொருள் செலவு",
        "Labour Cost": "தொழிலாளர் செலவு",
        "Production Cost": "உற்பத்தி செலவு",
        "Market Information": "சந்தை தகவல்",
        "Get Price Recommendation": "விலை பரிந்துரையைப் பெறுங்கள்",
        "Recommended Price": "பரிந்துரைக்கப்பட்ட விலை",
        "Price Range": "விலை வரம்பு",
        "Reason": "காரணம்",
        "Market Consideration": "சந்தை கருத்து",

        "Market Linkage": "சந்தை இணைப்பு",
        "Connect your products with potential buyers": "உங்கள் தயாரிப்புகளை சாத்தியமான வாங்குபவர்களுடன் இணைக்கவும்",
        "Product Showcase": "தயாரிப்பு காட்சி",
        "Buyer Visibility": "வாங்குபவர் பார்வை",
        "Market Visibility": "சந்தை பார்வை",

        "Account Settings": "கணக்கு அமைப்புகள்",
        "Select Language": "மொழியைத் தேர்ந்தெடுக்கவும்",
        "English": "ஆங்கிலம்",
        "Tamil": "தமிழ்",
        "Kannada": "கன்னடம்",
        "Telugu": "தெலுங்கு",
        "Hindi": "இந்தி",
        "Malayalam": "மலையாளம்",
        "Language updated successfully": "மொழி வெற்றிகரமாக மாற்றப்பட்டது",

        "Login": "உள்நுழைவு",
        "Register": "பதிவு",
        "Password": "கடவுச்சொல்",
        "Confirm Password": "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
        "Create Account": "கணக்கை உருவாக்கு",
        "Already have an account?": "ஏற்கனவே கணக்கு உள்ளதா?",
        "Don't have an account?": "கணக்கு இல்லையா?",
        "Login to CRAFTNOVA AI": "CRAFTNOVA AI-ல் உள்நுழையவும்",
        "Create your CRAFTNOVA AI account": "உங்கள் CRAFTNOVA AI கணக்கை உருவாக்கவும்",

        "AI-powered marketplace assistant for artisans": "கைவினைஞர்களுக்கான AI சந்தை உதவியாளர்",
        "Craft Business": "கைவினை வணிகம்",
        "Handmade Products": "கைவினை தயாரிப்புகள்"
    },

    "Kannada": {
        "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        "Products": "ಉತ್ಪನ್ನಗಳು",
        "Add Product": "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        "Inventory": "ದಾಸ್ತಾನು",
        "AI Tools": "AI ಸಾಧನಗಳು",
        "Image Enhancer": "ಚಿತ್ರ ಸುಧಾರಕ",
        "Voice Input": "ಧ್ವನಿ ಇನ್‌ಪುಟ್",
        "Smart Catalog": "ಸ್ಮಾರ್ಟ್ ಕ್ಯಾಟಲಾಗ್",
        "AI Pricing": "AI ಬೆಲೆ ನಿರ್ಧಾರ",
        "Business": "ವ್ಯಾಪಾರ",
        "Market": "ಮಾರುಕಟ್ಟೆ",
        "Account": "ಖಾತೆ",
        "Settings": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "Logout": "ಲಾಗ್‌ಔಟ್",
        "Welcome": "ಸ್ವಾಗತ",
        "Name": "ಹೆಸರು",
        "Email": "ಇಮೇಲ್",
        "Language": "ಭಾಷೆ",
        "Craft Category": "ಕರಕುಶಲ ವರ್ಗ",
        "Business Name": "ವ್ಯಾಪಾರದ ಹೆಸರು",
        "Recent Products": "ಇತ್ತೀಚಿನ ಉತ್ಪನ್ನಗಳು",
        "Product Name": "ಉತ್ಪನ್ನದ ಹೆಸರು",
        "Category": "ವರ್ಗ",
        "Material": "ವಸ್ತು",
        "Color": "ಬಣ್ಣ",
        "Size": "ಗಾತ್ರ",
        "Description": "ವಿವರಣೆ",
        "Price": "ಬೆಲೆ",
        "Actions": "ಕ್ರಿಯೆಗಳು",
        "Save": "ಉಳಿಸಿ",
        "Save Changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
        "Delete": "ಅಳಿಸಿ",
        "Search": "ಹುಡುಕಿ",
        "Submit": "ಸಲ್ಲಿಸಿ",
        "Back": "ಹಿಂದೆ",
        "Generate": "ರಚಿಸಿ",
        "Upload": "ಅಪ್‌ಲೋಡ್",
        "Download": "ಡೌನ್‌ಲೋಡ್",
        "Add New Product": "ಹೊಸ ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
        "Product Details": "ಉತ್ಪನ್ನ ವಿವರಗಳು",
        "Product Image": "ಉತ್ಪನ್ನದ ಚಿತ್ರ",
        "Inventory Management": "ದಾಸ್ತಾನು ನಿರ್ವಹಣೆ",
        "Enhance Product Image": "ಉತ್ಪನ್ನದ ಚಿತ್ರವನ್ನು ಸುಧಾರಿಸಿ",
        "Original Image": "ಮೂಲ ಚಿತ್ರ",
        "Enhanced Image": "ಸುಧಾರಿತ ಚಿತ್ರ",
        "Enhance Image": "ಚಿತ್ರವನ್ನು ಸುಧಾರಿಸಿ",
        "Voice Product Entry": "ಧ್ವನಿ ಉತ್ಪನ್ನ ನಮೂದು",
        "Start Voice Input": "ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಪ್ರಾರಂಭಿಸಿ",
        "Stop Voice Input": "ಧ್ವನಿ ಇನ್‌ಪುಟ್ ನಿಲ್ಲಿಸಿ",
        "Product Type": "ಉತ್ಪನ್ನದ ಪ್ರಕಾರ",
        "Transcript": "ಧ್ವನಿ ಪಠ್ಯ",
        "Generate Catalog": "ಕ್ಯಾಟಲಾಗ್ ರಚಿಸಿ",
        "Catalog Result": "ಕ್ಯಾಟಲಾಗ್ ಫಲಿತಾಂಶ",
        "AI Pricing Assistant": "AI ಬೆಲೆ ಸಹಾಯಕ",
        "Material Cost": "ವಸ್ತು ವೆಚ್ಚ",
        "Labour Cost": "ಕಾರ್ಮಿಕ ವೆಚ್ಚ",
        "Production Cost": "ಉತ್ಪಾದನಾ ವೆಚ್ಚ",
        "Market Information": "ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ",
        "Get Price Recommendation": "ಬೆಲೆ ಶಿಫಾರಸು ಪಡೆಯಿರಿ",
        "Recommended Price": "ಶಿಫಾರಸು ಮಾಡಿದ ಬೆಲೆ",
        "Price Range": "ಬೆಲೆ ವ್ಯಾಪ್ತಿ",
        "Reason": "ಕಾರಣ",
        "Market Consideration": "ಮಾರುಕಟ್ಟೆ ಪರಿಗಣನೆ",
        "Market Linkage": "ಮಾರುಕಟ್ಟೆ ಸಂಪರ್ಕ",
        "Account Settings": "ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        "Select Language": "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        "English": "ಇಂಗ್ಲಿಷ್",
        "Tamil": "ತಮಿಳು",
        "Kannada": "ಕನ್ನಡ",
        "Telugu": "ತೆಲುಗು",
        "Hindi": "ಹಿಂದಿ",
        "Malayalam": "ಮಲಯಾಳಂ",
        "Language updated successfully": "ಭಾಷೆ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಯಿಸಲಾಗಿದೆ",
        "Login": "ಲಾಗಿನ್",
        "Register": "ನೋಂದಣಿ",
        "Password": "ಪಾಸ್‌ವರ್ಡ್",
        "Confirm Password": "ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
        "Create Account": "ಖಾತೆ ರಚಿಸಿ",
        "Already have an account?": "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
        "Don't have an account?": "ಖಾತೆ ಇಲ್ಲವೇ?"
    },

    "Telugu": {
        "Dashboard": "డ్యాష్‌బోర్డ్",
        "Products": "ఉత్పత్తులు",
        "Add Product": "ఉత్పత్తిని జోడించండి",
        "Inventory": "నిల్వ",
        "AI Tools": "AI సాధనాలు",
        "Image Enhancer": "చిత్ర మెరుగుదల",
        "Voice Input": "వాయిస్ ఇన్‌పుట్",
        "Smart Catalog": "స్మార్ట్ క్యాటలాగ్",
        "AI Pricing": "AI ధర నిర్ణయం",
        "Business": "వ్యాపారం",
        "Market": "మార్కెట్",
        "Account": "ఖాతా",
        "Settings": "సెట్టింగ్స్",
        "Logout": "లాగ్ అవుట్",
        "Welcome": "స్వాగతం",
        "Name": "పేరు",
        "Email": "ఇమెయిల్",
        "Language": "భాష",
        "Craft Category": "క్రాఫ్ట్ వర్గం",
        "Business Name": "వ్యాపార పేరు",
        "Recent Products": "ఇటీవలి ఉత్పత్తులు",
        "Product Name": "ఉత్పత్తి పేరు",
        "Category": "వర్గం",
        "Material": "పదార్థం",
        "Color": "రంగు",
        "Size": "పరిమాణం",
        "Description": "వివరణ",
        "Price": "ధర",
        "Actions": "చర్యలు",
        "Save": "సేవ్ చేయండి",
        "Save Changes": "మార్పులను సేవ్ చేయండి",
        "Delete": "తొలగించండి",
        "Search": "వెతకండి",
        "Submit": "సమర్పించండి",
        "Back": "వెనుకకు",
        "Generate": "రూపొందించండి",
        "Upload": "అప్‌లోడ్",
        "Download": "డౌన్‌లోడ్",
        "Add New Product": "కొత్త ఉత్పత్తిని జోడించండి",
        "Product Details": "ఉత్పత్తి వివరాలు",
        "Product Image": "ఉత్పత్తి చిత్రం",
        "Inventory Management": "నిల్వ నిర్వహణ",
        "Enhance Product Image": "ఉత్పత్తి చిత్రాన్ని మెరుగుపరచండి",
        "Original Image": "అసలు చిత్రం",
        "Enhanced Image": "మెరుగుపరచిన చిత్రం",
        "Enhance Image": "చిత్రాన్ని మెరుగుపరచండి",
        "Voice Product Entry": "వాయిస్ ఉత్పత్తి నమోదు",
        "Start Voice Input": "వాయిస్ ఇన్‌పుట్ ప్రారంభించండి",
        "Stop Voice Input": "వాయిస్ ఇన్‌పుట్ ఆపండి",
        "Product Type": "ఉత్పత్తి రకం",
        "Transcript": "వాయిస్ పాఠ్యం",
        "Generate Catalog": "క్యాటలాగ్ రూపొందించండి",
        "Catalog Result": "క్యాటలాగ్ ఫలితం",
        "AI Pricing Assistant": "AI ధర సహాయకుడు",
        "Material Cost": "పదార్థ ఖర్చు",
        "Labour Cost": "కార్మిక ఖర్చు",
        "Production Cost": "ఉత్పత్తి ఖర్చు",
        "Market Information": "మార్కెట్ సమాచారం",
        "Get Price Recommendation": "ధర సిఫార్సు పొందండి",
        "Recommended Price": "సిఫార్సు చేసిన ధర",
        "Price Range": "ధర పరిధి",
        "Reason": "కారణం",
        "Market Consideration": "మార్కెట్ పరిశీలన",
        "Market Linkage": "మార్కెట్ అనుసంధానం",
        "Account Settings": "ఖాతా సెట్టింగ్స్",
        "Select Language": "భాషను ఎంచుకోండి",
        "English": "ఆంగ్లం",
        "Tamil": "తమిళం",
        "Kannada": "కన్నడ",
        "Telugu": "తెలుగు",
        "Hindi": "హిందీ",
        "Malayalam": "మలయాళం",
        "Language updated successfully": "భాష విజయవంతంగా మార్చబడింది",
        "Login": "లాగిన్",
        "Register": "నమోదు",
        "Password": "పాస్‌వర్డ్",
        "Confirm Password": "పాస్‌వర్డ్ నిర్ధారించండి",
        "Create Account": "ఖాతా సృష్టించండి",
        "Already have an account?": "ఇప్పటికే ఖాతా ఉందా?",
        "Don't have an account?": "ఖాతా లేదా?"
    },

    "Hindi": {
        "Dashboard": "डैशबोर्ड",
        "Products": "उत्पाद",
        "Add Product": "उत्पाद जोड़ें",
        "Inventory": "इन्वेंटरी",
        "AI Tools": "AI उपकरण",
        "Image Enhancer": "इमेज एन्हांसर",
        "Voice Input": "वॉइस इनपुट",
        "Smart Catalog": "स्मार्ट कैटलॉग",
        "AI Pricing": "AI मूल्य निर्धारण",
        "Business": "व्यवसाय",
        "Market": "बाज़ार",
        "Account": "खाता",
        "Settings": "सेटिंग्स",
        "Logout": "लॉग आउट",
        "Welcome": "स्वागत है",
        "Name": "नाम",
        "Email": "ईमेल",
        "Language": "भाषा",
        "Craft Category": "शिल्प श्रेणी",
        "Business Name": "व्यवसाय का नाम",
        "Recent Products": "हाल के उत्पाद",
        "Product Name": "उत्पाद का नाम",
        "Category": "श्रेणी",
        "Material": "सामग्री",
        "Color": "रंग",
        "Size": "आकार",
        "Description": "विवरण",
        "Price": "कीमत",
        "Actions": "कार्य",
        "Save": "सहेजें",
        "Save Changes": "परिवर्तन सहेजें",
        "Delete": "हटाएं",
        "Search": "खोजें",
        "Submit": "जमा करें",
        "Back": "वापस",
        "Generate": "बनाएं",
        "Upload": "अपलोड",
        "Download": "डाउनलोड",
        "Add New Product": "नया उत्पाद जोड़ें",
        "Product Details": "उत्पाद विवरण",
        "Product Image": "उत्पाद छवि",
        "Inventory Management": "इन्वेंटरी प्रबंधन",
        "Enhance Product Image": "उत्पाद छवि सुधारें",
        "Original Image": "मूल छवि",
        "Enhanced Image": "सुधारी गई छवि",
        "Enhance Image": "छवि सुधारें",
        "Voice Product Entry": "वॉइस उत्पाद प्रविष्टि",
        "Start Voice Input": "वॉइस इनपुट शुरू करें",
        "Stop Voice Input": "वॉइस इनपुट रोकें",
        "Product Type": "उत्पाद प्रकार",
        "Transcript": "वॉइस टेक्स्ट",
        "Generate Catalog": "कैटलॉग बनाएं",
        "Catalog Result": "कैटलॉग परिणाम",
        "AI Pricing Assistant": "AI मूल्य सहायक",
        "Material Cost": "सामग्री लागत",
        "Labour Cost": "श्रम लागत",
        "Production Cost": "उत्पादन लागत",
        "Market Information": "बाज़ार जानकारी",
        "Get Price Recommendation": "मूल्य सुझाव प्राप्त करें",
        "Recommended Price": "अनुशंसित कीमत",
        "Price Range": "मूल्य सीमा",
        "Reason": "कारण",
        "Market Consideration": "बाज़ार विचार",
        "Market Linkage": "बाज़ार संपर्क",
        "Account Settings": "खाता सेटिंग्स",
        "Select Language": "भाषा चुनें",
        "English": "अंग्रेज़ी",
        "Tamil": "तमिल",
        "Kannada": "कन्नड़",
        "Telugu": "तेलुगु",
        "Hindi": "हिंदी",
        "Malayalam": "मलयालम",
        "Language updated successfully": "भाषा सफलतापूर्वक बदल दी गई",
        "Login": "लॉगिन",
        "Register": "पंजीकरण",
        "Password": "पासवर्ड",
        "Confirm Password": "पासवर्ड की पुष्टि करें",
        "Create Account": "खाता बनाएं",
        "Already have an account?": "क्या आपके पास पहले से खाता है?",
        "Don't have an account?": "खाता नहीं है?"
    },

    "Malayalam": {
        "Dashboard": "ഡാഷ്ബോർഡ്",
        "Products": "ഉൽപ്പന്നങ്ങൾ",
        "Add Product": "ഉൽപ്പന്നം ചേർക്കുക",
        "Inventory": "ഇൻവെന്ററി",
        "AI Tools": "AI ഉപകരണങ്ങൾ",
        "Image Enhancer": "ചിത്ര മെച്ചപ്പെടുത്തൽ",
        "Voice Input": "വോയ്സ് ഇൻപുട്ട്",
        "Smart Catalog": "സ്മാർട്ട് കാറ്റലോഗ്",
        "AI Pricing": "AI വിലനിർണ്ണയം",
        "Business": "ബിസിനസ്",
        "Market": "വിപണി",
        "Account": "അക്കൗണ്ട്",
        "Settings": "ക്രമീകരണങ്ങൾ",
        "Logout": "ലോഗൗട്ട്",
        "Welcome": "സ്വാഗതം",
        "Name": "പേര്",
        "Email": "ഇമെയിൽ",
        "Language": "ഭാഷ",
        "Craft Category": "കരകൗശല വിഭാഗം",
        "Business Name": "ബിസിനസ് പേര്",
        "Recent Products": "സമീപകാല ഉൽപ്പന്നങ്ങൾ",
        "Product Name": "ഉൽപ്പന്നത്തിന്റെ പേര്",
        "Category": "വിഭാഗം",
        "Material": "മെറ്റീരിയൽ",
        "Color": "നിറം",
        "Size": "വലുപ്പം",
        "Description": "വിവരണം",
        "Price": "വില",
        "Actions": "പ്രവർത്തനങ്ങൾ",
        "Save": "സംരക്ഷിക്കുക",
        "Save Changes": "മാറ്റങ്ങൾ സംരക്ഷിക്കുക",
        "Delete": "ഇല്ലാതാക്കുക",
        "Search": "തിരയുക",
        "Submit": "സമർപ്പിക്കുക",
        "Back": "തിരികെ",
        "Generate": "സൃഷ്ടിക്കുക",
        "Upload": "അപ്‌ലോഡ്",
        "Download": "ഡൗൺലോഡ്",
        "Add New Product": "പുതിയ ഉൽപ്പന്നം ചേർക്കുക",
        "Product Details": "ഉൽപ്പന്ന വിശദാംശങ്ങൾ",
        "Product Image": "ഉൽപ്പന്ന ചിത്രം",
        "Inventory Management": "ഇൻവെന്ററി മാനേജ്മെന്റ്",
        "Enhance Product Image": "ഉൽപ്പന്ന ചിത്രം മെച്ചപ്പെടുത്തുക",
        "Original Image": "യഥാർത്ഥ ചിത്രം",
        "Enhanced Image": "മെച്ചപ്പെടുത്തിയ ചിത്രം",
        "Enhance Image": "ചിത്രം മെച്ചപ്പെടുത്തുക",
        "Voice Product Entry": "വോയ്സ് ഉൽപ്പന്ന എൻട്രി",
        "Start Voice Input": "വോയ്സ് ഇൻപുട്ട് ആരംഭിക്കുക",
        "Stop Voice Input": "വോയ്സ് ഇൻപുട്ട് നിർത്തുക",
        "Product Type": "ഉൽപ്പന്ന തരം",
        "Transcript": "വോയ്സ് ടെക്സ്റ്റ്",
        "Generate Catalog": "കാറ്റലോഗ് സൃഷ്ടിക്കുക",
        "Catalog Result": "കാറ്റലോഗ് ഫലം",
        "AI Pricing Assistant": "AI വില സഹായി",
        "Material Cost": "മെറ്റീരിയൽ ചെലവ്",
        "Labour Cost": "തൊഴിൽ ചെലവ്",
        "Production Cost": "ഉൽപ്പാദന ചെലവ്",
        "Market Information": "വിപണി വിവരങ്ങൾ",
        "Get Price Recommendation": "വില ശുപാർശ നേടുക",
        "Recommended Price": "ശുപാർശ ചെയ്യുന്ന വില",
        "Price Range": "വില പരിധി",
        "Reason": "കാരണം",
        "Market Consideration": "വിപണി പരിഗണന",
        "Market Linkage": "വിപണി ബന്ധം",
        "Account Settings": "അക്കൗണ്ട് ക്രമീകരണങ്ങൾ",
        "Select Language": "ഭാഷ തിരഞ്ഞെടുക്കുക",
        "English": "ഇംഗ്ലീഷ്",
        "Tamil": "തമിഴ്",
        "Kannada": "കന്നഡ",
        "Telugu": "തെലുങ്ക്",
        "Hindi": "ഹിന്ദി",
        "Malayalam": "മലയാളം",
        "Language updated successfully": "ഭാഷ വിജയകരമായി മാറ്റി",
        "Login": "ലോഗിൻ",
        "Register": "രജിസ്റ്റർ",
        "Password": "പാസ്‌വേഡ്",
        "Confirm Password": "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
        "Create Account": "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        "Already have an account?": "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?",
        "Don't have an account?": "അക്കൗണ്ട് ഇല്ലേ?"
    }
}


def translate(key, language="English"):
    language = language if language in TRANSLATIONS else "English"

    if key in TRANSLATIONS[language]:
        return TRANSLATIONS[language][key]

    if key in TRANSLATIONS["English"]:
        return TRANSLATIONS["English"][key]

    return key


def get_language_name(language):
    names = {
        "English": "English",
        "Tamil": "தமிழ்",
        "Kannada": "ಕನ್ನಡ",
        "Telugu": "తెలుగు",
        "Hindi": "हिन्दी",
        "Malayalam": "മലയാളം"
    }

    return names.get(language, language)